# Generated by Django 4.0.5 on 2022-06-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.ImageField(upload_to='images/', verbose_name='Изображение товара')),
                ('title', models.CharField(max_length=100, verbose_name='Название товара')),
                ('details', models.TextField(verbose_name='Описание товара')),
                ('price', models.DecimalField(verbose_name='Цена товара', max_digits=10, decimal_places=2)),
            ],
        ),
    ]
